Models/dbEEHAutomotor/Siniestro.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace EEHAutomotor.Models.dbEEHAutomotor
{
    public partial class Siniestro
    {
        public Siniestro()
        {
            DocSiniestro = new HashSet<DocSiniestro>();
        }

        public int IdSiniestro { get; set; }
        public int IdVehiculo { get; set; }
        public DateTime FechaOcurrio { get; set; }
        public DateTime FechaCreacion { get; set; }
        public int idSector { get; set; }
        public int IdConductor { get; set; }
        public bool ExistenTerceros { get; set; }
        public string LugarEvento { get; set; }
        public string DescripDanio { get; set; }
        public string RelatoSiniestro { get; set; }
        public decimal CostoReparacion { get; set; }
        public decimal? CostoTerceros { get; set; }
        public string Responsabilidad { get; set; }
        public int VelocidadTransitada { get; set; }
        public string DatosTercero { get; set; }
        public string UsuarioCrea { get; set; }

        public virtual Conductor IdConductorNavigation { get; set; }
        public virtual Vehiculo IdVehiculoNavigation { get; set; }
        public virtual Sector idSectorNavigation { get; set; }
        public virtual ICollection<DocSiniestro> DocSiniestro { get; set; }
    }
}

Controllers/SiniestroController.cs
using EEHAutomotor.DTO;
using EEHAutomotor.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Threading.Tasks;

namespace EEHAutomotor.Controllers
{
    public class SiniestroController : Controller
    {
        readonly ISiniestros _Siniestro;
        readonly IGenerales _gen;
        readonly IFun _fun;
        private ISessionUsr _Session;

        public SiniestroController(ISessionUsr session, ISiniestros Siniestros, IGenerales generales, IFun fun)
        {
            _Session = session;
            _Siniestro = Siniestros;
            _gen = generales;
            _fun = fun;
        }

        // GET: SiniestroController
        public ActionResult Index()
        {
            var l = _Siniestro.GetSiniestrosDto();
            return View(l);
        }

        public ActionResult Detail(string id)
        {
            var l = _Siniestro.GetSiniestrosDto(int.Parse(_fun.DecodeBase64(id)));
            //CargaListadoViewData();
            return View(l.FirstOrDefault());
        }
        public async Task<IActionResult> DownloadFilesSini(string id)
        {
            var achivos = _Siniestro.GetFilesDto(id);

            var zipFileMemoryStream = new MemoryStream();

            using (ZipArchive archive = new ZipArchive(zipFileMemoryStream, ZipArchiveMode.Update, leaveOpen: true))
            {
                foreach (var FilePath in achivos)
                {
                    var botFileName = Path.GetFileName(FilePath.Ruta);
                    var entry = archive.CreateEntry(botFileName);
                    using (var entryStream = entry.Open())
                    using (var fileStream = System.IO.File.OpenRead(FilePath.Ruta))
                    {
                        await fileStream.CopyToAsync(entryStream);
                    }
                }
            }

            zipFileMemoryStream.Seek(0, SeekOrigin.Begin);
            return File(zipFileMemoryStream, "application/octet-stream", "Archivos_Siniestro.zip");
        }

        // GET: SiniestroController/Create
        public ActionResult Create()
        {
            CargaListadoViewData();
            return View();
        }

        // POST: SiniestroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SiniestroDto dto)
        {
            try
            {
                var archivos = new List<FileDto>();
                foreach (var (f, i) in Request.Form.Files.Select((v, i) => (v, i)))
                {
                    string nom = "File_" + (i + 1).ToString() + "_" + DateTime.Now.ToString("yyyyMMddHHmmss");
                    var archivo = _fun.SaveFile(f, 3, nom);
                    if (archivo != null)
                    {
                        archivos.Add(archivo);
                    }
                }

                dto.UsuarioCrea =_Session.GetUsrLogged().UsuarioSoeeh;

                var sin = new SiniestroInsertDto();
                sin.Siniestro = dto;
                sin.Archivos = new List<FileDto>(archivos);

                var res = _Siniestro.PutSiniestro(sin);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _gen.PutError(ex.GetBaseException().Message, this.GetType().Name);
                return View();
            }
        }

        /********************************MÉTODOS*********************************/
        private void CargaListadoViewData()
        {
            List<SelectListItem> ListSector = new List<SelectListItem>();
            ListSector.AddRange(new SelectList(_gen.GeListaSectores(), "value", "label"));
            ListSector.Insert(0, new SelectListItem { Text = "*** Seleccionar ***", Value = "" });
            ViewData["ListSector"] = ListSector.OrderBy(x => x.Text);

            List<SelectListItem> ListResponsabilidad = new List<SelectListItem>();
            ListResponsabilidad.AddRange(new SelectList(_Siniestro.GetListaResponsabilidad(), "value", "label"));
            ListResponsabilidad.Insert(0, new SelectListItem { Text = "*** Seleccionar ***", Value = "" });
            ViewData["ListResponsabilidad"] = ListResponsabilidad.OrderBy(x => x.Text);
        }

    }
}

Views/Siniestro/Index.cshtml
@model IEnumerable<EEHAutomotor.DTO.SiniestroDto> 
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Administración de Siniestros</h1>

<br />
<p>
    <i class="la la-cc"></i> <a asp-action="Create">Crear Reporte Siniestro</a>
</p>


<!-- Inventario Placas Table -->
<div class="row match-height">
    <div id="divTbPlacas" class="col-12 col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title info">Siniestros</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
            </div>
            <div class="card-content mt-1">
                <div class="table-responsive">
                    <table class="table table-primary table-bordered bootstrap-3 compact" id="GridSiniestros" style="width:100%">
                        <thead>
                            <tr>
                                <th>IDSINIESTRO</th>
                                <th>PAU</th>
                                <th>COLOR</th>
                                <th>IDMARCA</th>
                                <th>MARCA</th>
                                <th>CATEGORIA</th>
                                <th>MODELO</th>
                                <th>VIN</th>
                                <th>MOTOR</th>
                                <th>PLACA</th>
                                <th>TARJETACOMBUSTIBLE</th>
                                <th>IDCONDUCTOR</th>
                                <th>IDENTIDAD</th>
                                <th>CONDUCTOR</th>
                                <th>TELEFONO</th>
                                <th>CIUDAD</th>
                                <th>FECHALICENCIAVENCE</th>
                                <th>FECHA OCURRIO</th>
                                <th>FECHA CREACION</th>
                                <th>IDSECTOR</th>
                                <th>SECTOR</th>
                                <th>EXISTENTERCEROS</th>
                                <th>EXISTEN TERCEROS</th>
                                <th>DESCRIPCIÓN DE DAÑO</th>
                                <th>RELATOSINIESTRO</th>
                                <th>COSTO REPARACIÓN</th>
                                <th>COSTOTERCEROS</th>
                                <th>RESPONSABILIDAD</th>
                                <th>VELOCIDADTRANSITADA</th>
                                <th>DATOSTERCERO</th>
                                <th>LUGAR EVENTO</th>
                                <th>ACCION</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                if (Model != null)
                                {
                                    @foreach (var item in Model)
                                    {
                            <tr>
                                @*col 0*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.IdSiniestro)
                                </td>
                                @*col 1*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.IdVehiculo)
                                </td>
                                @*col 2*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.Color)
                                </td>
                                @*col 3*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.IdMarca)
                                </td>
                                @*col 4*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.NomMarca)
                                </td>
                                @*col 5*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.Categoria)
                                </td>
                                @*col 6*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.ModeloDescrip)
                                </td>
                                @*col 7*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.VIN)
                                </td>
                                @*col 8*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.Motor)
                                </td>
                                @*col 9*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.CodPlaca)
                                </td>
                                @*col 10*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.TarjetaCombustible)
                                </td>
                                @*col 11*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.IdConductor)
                                </td>
                                @*col 12*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.Identidad)
                                </td>
                                @*col 13*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.NomConductor)
                                </td>
                                @*col 14*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.Telefono)
                                </td>
                                @*col 15*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ciudad)
                                </td>
                                @*col 16*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.FechaLicenciaVence)
                                </td>
                                @*col 17*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.FechaOcurrio)
                                </td>
                                @*col 18*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.FechaCreacion)
                                </td>
                                @*col 19*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.idSector)
                                </td>
                                @*col 20*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.Sector)
                                </td>
                                @*col 21*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.ExistenTerceros)
                                </td>
                                @*col 22*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.ExistenTercerosString)
                                </td>
                                @*col 23*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.DescripDanio)
                                </td>
                                @*col 24*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.RelatoSiniestro)
                                </td>
                                @*col 25*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.CostoReparacion)
                                </td>
                                @*col 26*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.CostoTerceros)
                                </td>
                                @*col 27*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.Responsabilidad)
                                </td>
                                @*col 28*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.VelocidadTransitada)
                                </td>
                                @*col 29*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.DatosTercero)
                                </td>
                                @*col 30*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.LugarEvento)
                                </td>
                                @*col 31*@
                                <td>
                                    @Html.ActionLink("Ver", "Detail", "Siniestro", routeValues: new { id = item.IdEncode }, htmlAttributes: new { @class = "btn btn-sm btn-info" })
                                </td>
                            </tr>
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Inventario Placas Table Ends -->

@section Styles {
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/datatables.min.css">
}

@section Scripts {
    <script src="~/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="~/js/JsSiniestros.js"></script>
    <!-- Datatable -->
    <script>
        $(function () {
            control = new ControlSiniestros(1);
        });
    </script>
}