Controllers/ExcesosController.cs
using EEHAutomotor.DTO;
using EEHAutomotor.Interfaces;
using ExcelDataReader;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EEHAutomotor.Controllers
{
    public class ExcesosController : Controller
    {
        readonly IFun _fun;
        IExcesos _excesos;

        public ExcesosController(IFun fun, IExcesos excesos)
        {
            _fun = fun;
            _excesos = excesos;
        }

        // GET: ExcesosController
        public ActionResult Index()
        {
            var excesos = _excesos.GetListaExcesosDto();
            return View(excesos);
        }

        // GET: ExcesosController/Details/5
        public ActionResult Details(string id)
        {
            var e = _excesos.GetExcesosDtoByIdEncode(id);
            return View(e);
        }

        // GET: ExcesosController/Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: ExcesosController/Create
       [HttpPost]
       [ValidateAntiForgeryToken]
        public ActionResult Create(ExcesoSave exceso)
        {
            var _ExcesoSave = new ExcesoSave();
            try
            {
                if (Request.Form.Files.Count==1)
                {
                    foreach (var (f, i) in Request.Form.Files.Select((v, i) => (v, i)))
                    {
                        _ExcesoSave = GetDataFromExcelFile(f);
                    }

                    if (_ExcesoSave.GuardadoOk)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return View(_ExcesoSave);
                    }
                }
                else
                {
                    _ExcesoSave.GuardadoOk = false;
                    _ExcesoSave.MsjSave = "Archivo NO válido!";
                    return View(_ExcesoSave);
                }
            }
            catch(Exception ex)
            {
                _ExcesoSave.GuardadoOk = false;
                _ExcesoSave.MsjSave = $"Archivo NO válido! (Error: {ex.Message})";
                return View(_ExcesoSave);
            }
        }

        private ExcesoSave GetDataFromExcelFile(IFormFile file)
        {
            var Exc = new ExcesoSave();
            try
            {
                int FilasArchivo = 0;
                System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

                if (Exc == null || Exc.ListaExcesoDto == null)
                {
                    using (var stream = new MemoryStream())
                    {
                        file.CopyTo(stream);
                        stream.Position = 0;

                        using (var reader = ExcelReaderFactory.CreateReader(stream))
                        {
                            var dataSet = reader.AsDataSet(new ExcelDataSetConfiguration
                            {
                                ConfigureDataTable = _ => new ExcelDataTableConfiguration
                                {
                                    UseHeaderRow = true // To set First Row As Column Names    
                                }
                            });

                            if (dataSet.Tables[0].Rows.Count > 1)
                            {
                                //Conteo de filas que vienen en archivo
                                FilasArchivo = dataSet.Tables[0].Rows.Count - 1;

                                var dataTable = dataSet.Tables[0];

                                //Obtener Lista de excesos DTO y Placas Error
                                Exc = _excesos.GetListaExcesosDtoByExcel(dataTable);

                                /// Si no hay Placas Error Y
                                /// cantidades de placas en archivo con cantidad de placas DTO
                                /// son iguales, entonces procede a guardar el archivo correcto.
                                if ((FilasArchivo == Exc.ListaExcesoDto.Count) && Exc.ListaPlacaError.Count == 0)
                                {
                                    Exc = _excesos.GuardarListaExcesosVelocidad(Exc);
                                }
                                else
                                {
                                    Exc.GuardadoOk = false;
                                    Exc.MsjSave = "Error en procesar archivo";
                                }
                            }
                            else
                            {
                                Exc.GuardadoOk = false;
                                Exc.MsjSave = "Archivo no contiene registros válidos.";
                            }
                        }
                    }
                }
                return Exc;
            }
            catch (Exception ex)
            {
                Exc.GuardadoOk = false;
                Exc.MsjSave = $"Archivo NO válido! (Error: {ex.Message})";
                return Exc;
            }
        }

    }
}

Views/Excesos/Index.cshtml
@model IEnumerable<EEHAutomotor.DTO.ExcesoDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Listado de Excesos de Velocidad</h1>
<!-- Excesos Table -->
<div class="row match-height">
    <div id="divTbVehiculos" class="col-12 col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title info">Reportes</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
            </div>
            <div class="card-content mt-1">
                <div class="table-responsive">
                    <table class="table table-primary table-bordered bootstrap-3 compact" id="GridReportes" style="width:100%">
                        <thead>
                            <tr>
                                <th>IdExceso</th>
                                <th>PAU</th>
                                <th>PLACA</th>
                                <th>COLOR</th>
                                <th>IdMarca</th>
                                <th>MARCA</th>
                                <th>CATEGORIA</th>
                                <th>MODELO</th>
                                <th>VIN</th>
                                <th>MOTOR</th>
                                <th>FECHA/HORA FIN</th>
                                <th>DURACIÓN</th>
                                <th>VELOCIDAD EXCESO</th>
                                <th>Localización</th>
                                <th>IdConductor</th>
                                <th>CONDUCTOR</th>
                                <th>CordXY</th>
                                <th>ACCION</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                if (Model != null)
                                {
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @*col 0*@
                                                @Html.DisplayFor(modelItem => item.IdExceso)
                                            </td>
                                            <td>
                                                @*col 1*@
                                                @Html.DisplayFor(modelItem => item.IdVehiculo)
                                            </td>
                                            <td>
                                                @*col 2*@
                                                @Html.DisplayFor(modelItem => item.CodPlaca)
                                            </td>
                                            <td>
                                                @*col 3*@
                                                @Html.DisplayFor(modelItem => item.Color)
                                            </td>
                                            <td>
                                                @*col 4*@
                                                @Html.DisplayFor(modelItem => item.IdMarca)
                                            </td>
                                            <td>
                                                @*col 5*@
                                                @Html.DisplayFor(modelItem => item.NomMarca)
                                            </td>
                                            <td>
                                                @*col 6*@
                                                @Html.DisplayFor(modelItem => item.Categoria)
                                            </td>
                                            <td>
                                                @*col 7*@
                                                @Html.DisplayFor(modelItem => item.Modelo)
                                            </td>
                                            <td>
                                                @*col 8*@
                                                @Html.DisplayFor(modelItem => item.VIN)
                                            </td>
                                            <td>
                                                @*col 9*@
                                                @Html.DisplayFor(modelItem => item.Motor)
                                            </td>
                                            <td>
                                                @*col 10*@
                                                @Html.DisplayFor(modelItem => item.FechaHoraFin)
                                            </td>
                                            <td>
                                                @*col 11*@
                                                00:@item.Duracion.ToString("mm:ss")
                                            </td>
                                            <td>
                                                @*col 12*@
                                                @Html.DisplayFor(modelItem => item.VelocidadExceso)
                                            </td>
                                            <td>
                                                @*col 13*@
                                                @Html.DisplayFor(modelItem => item.Localizacion)
                                            </td>
                                            <td>
                                                @*col 14*@
                                                @Html.DisplayFor(modelItem => item.IdConductor)
                                            </td>
                                            <td>
                                                @*col 15*@
                                                @Html.DisplayFor(modelItem => item.NomConductor)
                                            </td>
                                            <td>
                                                @*col 16*@
                                                @Html.DisplayFor(modelItem => item.CordXY)
                                            </td>
                                            <td>
                                                @*col 17*@
                                                @Html.ActionLink("Ver", "Details", "Excesos", routeValues: new { id = item.IdDecode }, htmlAttributes: new { @class = "btn btn-sm btn-info" })
                                            </td>
                                        </tr>
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Excesos Table Ends -->

@section Styles {
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/datatables.min.css">
}

@section Scripts {
    <script src="~/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="~/js/JsExcesos.js"></script>
    <!-- Datatable -->
    <script>
        $(function () {
            control = new ControlExcesos(1);
        });
    </script>
}