Controllers/FlotaController.cs
using EEHAutomotor.DTO;
using EEHAutomotor.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EEHAutomotor.Controllers
{
    public class FlotaController : Controller
    {
        readonly IVehiculos _vehiculos;
        readonly IGenerales _generales;
        public FlotaController(IVehiculos vehiculos, IGenerales generales)
        {
            _vehiculos = vehiculos;
            _generales = generales;
        }
        /****************************CRUD*********************************/
        public IActionResult Index()
        {
            var ListaVehiculos = _vehiculos.GetListaVehiculosDto();
            return View(ListaVehiculos);
        }
        public IActionResult Create()
        {
            List<SelectListItem> ListMarca = new List<SelectListItem>();
            ListMarca.AddRange(new SelectList(_vehiculos.GeListatMarcaVehiculos(), "value", "label"));
            ListMarca.Insert(0, new SelectListItem { Text = "*** Seleccionar ***", Value = "" });
            ViewData["ListMarca"] = ListMarca.OrderBy(x => x.Text);

            CargaListadoCreateUpdate();
            return View();
        }

        // GET: PlacaController/Edit/5
        public IActionResult Edit(string id)
        {
            CargaListadoCreateUpdate();
            var v = _vehiculos.GetVehiculoById(id);
            return View(v);
        }

        // POST: CitaController/Put
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PutPopVehiculo(VehiculoInsertDto vehiculo)
        {
            var resp = _vehiculos.PutVehiculo(vehiculo);
            return new JsonResult(resp);
        }
        
        /*****************************************************************/
        public JsonResult GetColores()
        {
            var lista = _vehiculos.GetListaColoresVehiculos();
            return Json(lista);
        }
        public JsonResult GetCategorias()
        {
            var listaColores = _vehiculos.GetListaCategoriaVehiculos();
            return Json(listaColores);
        }
        public JsonResult GetModelos()
        {
            var lista = _vehiculos.GetListaModeloVehiculos();
            return Json(lista);
        }

        /********************************MÉTODOS*********************************/
        [HttpPost]
        public int EvalExisteVinMotorPlaca(string par)
        {
            try
            {
                string[] datos = par.Split(",");
                int IntExiste = _vehiculos.GetExisteVehiculo(datos[0].ToLower().Trim(), datos[1].ToLower().Trim()) ? 1 : 0;
                return IntExiste;
            }
            catch (Exception)
            {
                return 0;
            }
        }
        private void CargaListadoCreateUpdate()
        {
            List<SelectListItem> Listlicencias = new List<SelectListItem>();
            Listlicencias.AddRange(new SelectList(_generales.GetListaTipoLicencia(), "value", "label"));
            Listlicencias.Insert(0, new SelectListItem { Text = "*** Seleccionar ***", Value = "" });
            ViewData["Listlicencias"] = Listlicencias.OrderBy(x => x.Text);

            List<SelectListItem> ListCombus = new List<SelectListItem>();
            ListCombus.AddRange(new SelectList(_generales.GetListaCombustibles(), "value", "label"));
            ListCombus.Insert(0, new SelectListItem { Text = "*** Seleccionar ***", Value = "" });
            ViewData["ListCombus"] = ListCombus.OrderBy(x => x.Text);

            List<SelectListItem> ListAsegura = new List<SelectListItem>();
            ListAsegura.AddRange(new SelectList(_generales.GeListaAseguradoras(), "value", "label"));
            ListAsegura.Insert(0, new SelectListItem { Text = "*** Seleccionar ***", Value = "" });
            ViewData["ListAsegura"] = ListAsegura.OrderBy(x => x.Text);
        }

    }
}

Views/Flota/Index.cshtml
@model IEnumerable<EEHAutomotor.DTO.VehiculoDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Inventario Flota de vehículos</h1>
<br />
<p>
    <i class="la la-automobile"></i> <a asp-action="Create">Crear Nuevo Vehículo</a>
</p>


<!-- Placas Table -->
<div class="row match-height">
    <div id="divTbVehiculos" class="col-12 col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title info">Vehículos</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
            </div>
            <div class="card-content mt-1">
                <div class="table-responsive">
                    <table class="table table-primary table-bordered bootstrap-3 compact" id="GridVechiculos" style="width:100%">
                        <thead>
                            <tr>
                                <th>PAU</th>
                                <th>VIN</th>
                                <th>MOTOR</th>
                                <th>PLACA</th>
                                <th>MARCA</th>
                                <th>MODELO</th>
                                <th>COLOR</th>
                                <th>PLACA ANTERIOR</th>
                                <th>CONDUCTOR</th>
                                <th>FECHA INGRESO</th>
                                <th>KM INGRESO</th>
                                <th>FECHA SALIDA</th>
                                <th>KM SALIDA</th>
                                <th>ESTADO</th>
                                <th>IdDecode</th>
                                <th>ACCION</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                if (Model != null)
                                {
                                    @foreach (var item in Model)
                                    {
                            <tr>
                                <td>
                                    @*col 0*@
                                    @Html.DisplayFor(modelItem => item.IdVehiculo)
                                </td>
                                <td>
                                    @*col 1*@
                                    @Html.DisplayFor(modelItem => item.Vin)
                                </td>
                                <td>
                                    @*col 2*@
                                    @Html.DisplayFor(modelItem => item.Motor)
                                </td>
                                <td>
                                    @*col 3*@
                                    @Html.DisplayFor(modelItem => item.Placa)
                                </td>
                                <td>
                                    @*col 4*@
                                    @Html.DisplayFor(modelItem => item.Marca)
                                </td>
                                <td>
                                    @*col 5*@
                                    @Html.DisplayFor(modelItem => item.Modelo)
                                </td>
                                <td>
                                    @*col 6*@
                                    @Html.DisplayFor(modelItem => item.Color)
                                </td>
                                <td>
                                    @*col 7*@
                                    @Html.DisplayFor(modelItem => item.PlacaAnterior)
                                </td>
                                <td>
                                    @*col 8*@
                                    @Html.DisplayFor(modelItem => item.Conductor)
                                </td>
                                <td>
                                    @*col 9*@
                                    @Html.DisplayFor(modelItem => item.FechaIngresoFlota)
                                </td>
                                <td>
                                    @*col 10*@
                                    @Html.DisplayFor(modelItem => item.KmIngreso)
                                </td>
                                <td>
                                    @*col 11*@
                                    @Html.DisplayFor(modelItem => item.FechaSalidaFlota)
                                </td>
                                <td>
                                    @*col 12*@
                                    @Html.DisplayFor(modelItem => item.KmSalida)
                                </td>
                                <td>
                                    @*col 13*@
                                    @if (item.Estado)
                                    {
                                        <div class="badge border-success success badge-border">ACTIVO</div>
                                    }
                                    else
                                    {
                                        <div class="badge border-danger danger badge-border">INACTIVO</div>
                                    }
                                </td>
                                <td>
                                    @*col 14*@
                                    @Html.DisplayFor(modelItem => item.IdEncode)
                                </td>
                                <td>
                                    @*col 15*@
                                    @Html.ActionLink("Ver" + (item.Estado ? " / Editar" : ""), "Edit", "Flota", routeValues: new { id = item.IdEncode }, htmlAttributes: new { @class = "btn btn-sm btn-info" })
                                </td>
                            </tr>
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Placas Table Ends -->

@section Styles {
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/datatables.min.css">
}

@section Scripts {
    <script src="~/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="~/js/JsVehiculos.js"></script>
    <!-- Datatable -->
    <script>
        $(function () {
            control = new ControlFlota(1);
        });
    </script>
}